apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pod.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pod.name }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: "enabled"
      labels:
        app: {{ .Values.pod.name }}
    spec:
      containers:
      - name: {{ .Values.pod.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
#      - name: filebeat
#        image: "docker.elastic.co/beats/filebeat:7.17.3"
#        volumeMounts:
#          - name: shared-logs
#            mountPath: /var/log/
#          - name: filebeat-config
#            mountPath: /usr/share/filebeat/filebeat.yml
#            subPath: filebeat.yml
#        resources:
#          requests:
#            cpu: 50m
#            memory: 100Mi
#          limits:
#            cpu: 100m
#            memory: 200Mi
      imagePullSecrets:
      - name: regcred
